# Generated by Django 3.1 on 2020-10-01 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20201001_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='pedido',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
            preserve_default=False,
        ),
    ]
