# Generated by Django 3.1 on 2020-10-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0007_usuario_fecha_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
