# Generated by Django 3.1 on 2020-09-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrarCliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registrar_Cliente',
            new_name='Cliente',
        ),
    ]
