# Generated by Django 3.1 on 2020-09-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrarCliente', '0002_auto_20200914_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=50)),
                ('cuil_cuit', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('vehiculo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('registro_conducir', models.CharField(max_length=100)),
                ('seguro', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
    ]
