# Generated by Django 3.1 on 2020-09-25 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrarCliente', '0004_auto_20200914_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Transportista',
        ),
    ]
